custom:
  name: application.yaml
  #######  custom validate properties
  host: 192.168.1.1
  port: 8080
  #######

server:
  host: 192.168.1.100

acme:
  enabled: true
  remote-address: 127.0.0.1
  security:
    username: xiaolian
    password: 123456
    roles: 
      - USER
      - ADMIN