custom:
  name: application.yaml
  #######  custom validate properties
  host: 192.168.1.1
  port: 8080
  #######

server:
  host: 192.168.1.100

acme:
  enabled: true
  remote-address: 127.0.0.1
  security:
    username: xiaolian
    password: 123456
    roles: 
      - USER
      - ADMIN


# ///////////////////////////logging////////////////////////////
#spring:
#  output:
#    ansi:
#      enabled: always

logging:
#  pattern:
#    console: '%clr(%d{yyyy-MM-dd HH:mm:ss}){yellow} [%clr(%thread){red}] %-5level --- %clr(%logger){green} | %msg%n'
  file:
#    max-history: 3
  group: 
    tomcat: org.apache.catalina, org.apache.coyote, org.apache.tomcat
  level: 
    tomcat: info
#  path: ./logs
# ///////////////////////////logging////////////////////////////

spring:
  messages:
    basename: i18n/messages
    cache-duration: 3600  # 单位秒
    encoding: UTF-8
  