custom:
  name: application.yaml
  #######  custom validate properties
  host: 192.168.1.1
  port: 8080
  #######

server:
  host: 192.168.1.100

acme:
  enabled: true
  remote-address: 127.0.0.1
  security:
    username: xiaolian
    password: 123456
    roles: 
      - USER
      - ADMIN


# ///////////////////////////logging////////////////////////////
#spring:
#  output:
#    ansi:
#      enabled: always

logging:
#  pattern:
#    console: '%clr(%d{yyyy-MM-dd HH:mm:ss}){yellow} [%clr(%thread){red}] %-5level --- %clr(%logger){green} | %msg%n'
  file:
#    max-history: 3
  group: 
    tomcat: org.apache.catalina, org.apache.coyote, org.apache.tomcat
  level: 
    tomcat: info
#  path: ./logs
# ///////////////////////////logging////////////////////////////

# ////////////////////////// i18n /////////////////////////////
spring:
  messages:
    basename: i18n/messages
    cache-duration: 3600  # 单位秒
    encoding: UTF-8

# ///////////////////////// static resources ///////////////////////////
  mvc:
#    static-path-pattern: /resources/**
    resources:
      static-locations: classpath:/static/, classpath:/app/
  
# ////////////////////////Path Matching & Content Negotiation ///////////////  
    contentnegotiation:
      favor-parameter: true
      media-types:
        plain: text/plain
        xml: text/xml
      favor-path-extension: true
    pathmatch:
  #      use-suffix-pattern: true
      use-registered-suffix-pattern: true

# //////////////////////////// redis ///////////////////////////////////
  redis:
    host: 192.168.3.201
#    password: 123456
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 300